spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "Baseline for existing database"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
springdoc:
  swagger-ui:
    path: /api-docs/swagger-ui.html


server:
  port: 8083
